---
# Ansible Task making sure the 15-minute inactivity is set to 900
# Uses the /etc/profile.d directory which stores shell scripts that Exec when login to machine.

# First control with vuln-ID: 234812

- name: Ensure session lock after 15-minute inactivity
  hosts: [OpenSUSE]
  become: yes

  tasks:
    - name: Check if /etc/profile.d/autologout.sh exists
      stat:
        path: /etc/profile.d/autologout.sh
      register: file_stat

    - name: Create /etc/profile.d/autologout.sh if it doesn't exist
      file:
        path: /etc/profile.d/autologout.sh
        state: touch
        mode: '0755'
      when: not file_stat.stat.exists

    - name: Ensure correct content in /etc/profile.d/autologout.sh
      blockinfile:
        path: /etc/profile.d/autologout.sh
        create: yes
        block: |
          TMOUT=900
          readonly TMOUT
          export TMOUT

