---
- name: Ensure session lock after 15-minute inactivity
  hosts: your_suse_host
  become: yes

  tasks:
    - name: Create /etc/profile.d/autologout.sh if it doesn't exist
      file:
        path: /etc/profile.d/autologout.sh
        state: touch
        mode: '0755'

    - name: Ensure correct content in /etc/profile.d/autologout.sh
      blockinfile:
        path: /etc/profile.d/autologout.sh
        create: yes
        block: |
          TMOUT=900
          readonly TMOUT
          export TMOUT
