---
- hosts: 192.168.1.15

  tasks:
    ---
- name: Ensure vsftpd is not installed
  hosts: your_opensuse_host
  become: yes

  tasks:
    - name: Check if vsftpd is installed
      command: zypper info vsftpd | grep Installed
      register: vsftpd_installed
      ignore_errors: true

    - name: Remove vsftpd
      command: zypper remove -y vsftpd
      when: "'Installed:' in vsftpd_installed.stdout"
