---
- name: Install kubectl on OpenSUSE Leap 15
  hosts: OpenSUSE
  become: true
  tasks:
    - name: Remove existing Kubernetes repository (if exists)
      command: zypper rr kubernetes
      ignore_errors: yes

    - name: Add Kubernetes repository
      command: zypper ar -f https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 kubernetes

    - name: Refresh all zypper repositories
      command: zypper refresh

    - name: Install kubectl
      zypper:
        name: kubectl
        state: present

    - name: Verify kubectl version
      command: kubectl version --client
      register: result

    - name: Show kubectl version
      debug:
        var: result.stdout_lines
