---

 tasks:
     - name: Ensure password policy is enforced
       pamd:
         name: common-password
         type: password
         control: requisite
         module_path: pam_pwquality.so
         new_type: password
         new_control: requisite
         new_module_path: pam_pwquality.so
         module_arguments: 'retry=3 minlen=15 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1'

...
