---
- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: [OpenSUSE]
  tasks:
    - name: Gather facts for OpenSUSE
      ansible.builtin.setup:
        gather_subset:
          - distribution
          - distribution_major_version
          - distribution_version
          - architecture
          - interfaces
      register: ansible_facts

    - name: Display the facts
      debug:
        var: ansible_facts
