---
## Gather ALL the facts for OpenSUSE machine

- name: Network Getting Started First Playbook
  gather_facts: true
  hosts: [OpenSUSE]
  tasks:
    - name: Gather facts for OpenSUSE
      ansible.builtin.setup:
      register: ansible_facts

    - name: Display the facts
      debug:
        var: ansible_facts
