- name: Enforcing SELinux
  hosts: [OpenSUSE]
  tasks:
    - name: Enforce SELinux
      ansible.posix.selinux:
        state: enforcing
        policy: targeted
      enabled: yes

    - name: Reboot the machine
      ansible.builtin.reboot:
