- name: Enforcing SELinux
  hosts: OpenSUSE
  become: yes

  tasks:
    - name: Enforce SELinux
      ansible.posix.selinux:
        state: enforcing
        policy: targeted

    - name: Reboot the machine
      ansible.builtin.reboot:
